// dish_reference.dart

const Map<String, List<Map<String, String>>> dishReferenceData = {
  "Brunei": [
    {"name": "Ambuyat", "url": "https://worldfood.guide/dish/ambuyat/"},
    {"name": "Ayam Penyet", "url": "https://babe.com.my/nasi-kandar-recipe-penang-style-rice-with-assorted-curries/"},
    {"name": "Daging Masak Hitam", "url": "https://babe.com.my/daging-masak-hitam-recipe-braised-beef-in-dark-soy-sauce/"},
    {"name": "Hati Buyah", "url": "https://worldfood.guide/dish/hati_buyah/"},
    {"name": "Kelupis", "url": "https://www.tasteatlas.com/kelupis"},
    {"name": "Nasi Katok", "url": "https://www.kikkoman.com/en/cookbook/recipe/00055377.html"},
    {"name": "Pulut Panggang", "url": "https://worldfood.guide/dish/pulut_panggang/"},
    {"name": "Serunding", "url": "https://commons.wikimedia.org/wiki/Special:MediaSearch?type=image&search=Serunding"},
    {"name": "Soto", "url": "https://trvlguides.com/articles/brunei-food-guide"},
    {"name": "Wajid", "url": "https://commons.wikimedia.org/wiki/File:Wajid.jpg"},
  ],
  "Cambodia": [
    {"name": "Amok Trey", "url": "https://www.tasteatlas.com/amok-trey"},
    {"name": "Bai Sach Chrouk", "url": "https://www.196flavors.com/cambodia-bai-sach-chrouk/?srsltid=AfmBOooNlUMG9zk7UZMwLrB7UzoRRi8AoVw7ODdLd_G5imnU-5GSpKXO"},
    {"name": "Cha Kroeung Sach Ko", "url": "https://grantourismotravels.com/cambodian-lemongrass-chicken-stir-fry-recipe/"},
    {"name": "Khmer Red Curry", "url": "https://allpointseast.com/travel-blog/cambodia/khmer-red-curry/"},
    {"name": "Kuy Teav", "url": "https://grantourismotravels.com/cambodian-kuy-teav-recipe/"},
    {"name": "Lok Lak", "url": "https://www.simplyrecipes.com/lok-lak-shaking-beef-recipe-7089865"},
    {"name": "Nom Banh Chok", "url": "https://angkorchef.com/2024/10/nom-banh-chok/"},
    {"name": "Num Ansom", "url": "https://amcarmenskitchen.com/2021/02/24/num-ansom-chek-rolled-banana-rice-cake/"},
    {"name": "Prahok", "url": "https://kroya.restaurant/glossary/prahok"},
    {"name": "Samlor Machu", "url": "https://angkorchef.com/2019/12/somlaw-machu-kroeung/"},
  ],
  "Indonesia": [
    {"name": "Ayam goreng", "url": "https://delishglobe.com/recipe/indonesian-ayam-goreng-fried-chicken/"},
    {"name": "Bakso", "url": "https://delishglobe.com/recipe/indonesian-bakso-meatball-soup/"},
    {"name": "Gado-Gado", "url": "https://www.seriouseats.com/gado-gado-indonesian-salad-with-peanut-sauce-8646793"},
    {"name": "Nasi Goreng", "url": "https://amcarmenskitchen.com/2021/05/05/nasi-goreng-indonesian-fried-rice/"},
    {"name": "Nasi Padang", "url": "https://moderndiplomacy.eu/2021/11/13/strengthening-indonesias-public-diplomacy-through-nasi-padang/"},
    {"name": "Pempek", "url": "https://indonesiaexpat.id/lifestyle/food-drink/pempek-palembangs-iconic-food/"},
    {"name": "Rawon", "url": "https://www.tastingtable.com/1416881/rawon-indonesian-beef-soup-ingredient-keluak-nut/"},
    {"name": "Rendang", "url": "https://tasteasianfood.com/beef-rendang-recipe/"},
    {"name": "Satay", "url": "https://asianinspirations.com.au/recipes/indonesian-chicken-satay/"},
    {"name": "Soto Ayam", "url": "https://www.wokandskillet.com/indonesian-chicken-soup-soto-ayam/"},
  ],
  "Laos": [
    {"name": "Jeow Bong", "url": "https://worldfood.guide/dish/jeow_bong/"},
    {"name": "Khao Piak Sen", "url": "https://worldfood.guide/dish/khao_piak_sen/"},
    {"name": "Khao Soi Lao", "url": "https://worldfood.guide/dish/khao_poon/"},
    {"name": "Laap", "url": "https://www.asiakingtravel.com/blog/lao-lucky-food.html"},
    {"name": "Mok Pa", "url": "https://worldfood.guide/dish/mok_pa/"},
    {"name": "Or Lam", "url": "https://worldfood.guide/dish/or_lam/"},
    {"name": "Ping Ka", "url": "https://asianinspirations.com.au/recipes/lao-grilled-chicken-ping-gai/"},
    {"name": "Sai Oua", "url": "https://worldfood.guide/dish/sai_oua/"},
    {"name": "Sticky Rice", "url": "https://www.internationalcuisine.com/laotian-sticky-rice/"},
    {"name": "Tam Mak Hoong", "url": "https://worldfood.guide/dish/tam_mak_houng/"},
  ],
  "Malaysia": [
    {"name": "Cendol", "url": "https://www.saveur.com/malaysia-cendol-shaved-ice-dessert/"},
    {"name": "Char kway teow", "url": "https://www.marionskitchen.com/easy-char-kway-teow/"},
    {"name": "Hainanese Chicken Rice", "url": "https://www.marionskitchen.com/easy-one-pot-hainanese-chicken-rice/"},
    {"name": "Laksa", "url": "https://asianinspirations.com.au/recipes/laksa-fried-rice/"},
    {"name": "Mee Goreng", "url": "https://roadsandkingdoms.com/2016/revisiting-a-favorite-breakfast-half-a-century-later/"},
    {"name": "Nasi Kandar", "url": "https://babe.com.my/nasi-kandar-recipe-penang-style-rice-with-assorted-curries/"},
    {"name": "Nasi Lemak", "url": "https://www.tasteatlas.com/nasi-lemak"},
    {"name": "Rendang", "url": "https://asianinspirations.com.au/recipes/malaysian-beef-rendang/"},
    {"name": "Roti canai", "url": "https://www.marionskitchen.com/malaysian-roti-canai/"},
    {"name": "Satay", "url": "https://www.taste.com.au/recipes/malaysian-satay/4c307b3e-030a-400e-ac58-d01ea5c22032"},
  ],
  "Myanmar": [
    {"name": "Hto-Hpu Nwe", "url": "https://en.wikipedia.org/wiki/Hto-hpu_nwe"},
    {"name": "Kyay Oh", "url": "https://www.tasteatlas.com/kyay-oh"},
    {"name": "Lahpet Thoke", "url": "https://delishglobe.com/recipe/burmese-laphet-thoke/"},
    {"name": "Mohinga", "url": "https://www.tastingtable.com/686384/burmese-breakfast-stew-recipe/"},
    {"name": "Mont Lone Yay Paw", "url": "https://en.wikipedia.org/wiki/Mont_lone_yay_baw"},
    {"name": "Nangyi Thoke", "url": "https://en.wikipedia.org/wiki/Nangyi_thoke"},
    {"name": "Ngapi", "url": "https://delishglobe.com/recipe/burmese-ohn-no-khao-swe/"},
    {"name": "Ohn No Khao Swe", "url": "https://delishglobe.com/recipe/burmese-ohn-no-khao-swe/"},
    {"name": "Shan Noodles", "url": "https://www.gomyanmartours.com/shan-noodles-one-best-burmese-cuisine/"},
    {"name": "Si Htamin", "url": "https://en.wikipedia.org/wiki/Si_htamin"},
  ],
  "Philippines": [
    {"name": "Adobo", "url": "https://www.thekitchn.com/filipino-chicken-adobo-recipe-23652486"},
    {"name": "Bicol Express", "url": "https://panlasangpinoy.com/bicol-express/"},
    {"name": "Bulalo", "url": "https://panlasangpinoy.com/bulalo-stewed-beef-shank/"},
    {"name": "Halo-Halo", "url": "https://www.bonappetit.com/recipe/halo-halo?srsltid=AfmBOoqqPpGG5nHBuJ25HP6lvynNPrZNWQnltxIIXzSGxgjbC0velY9_"},
    {"name": "Kare-Kare", "url": "https://simplybakings.com/vegan-kare-kare-delicious-easy/"},
    {"name": "Lechon", "url": "https://www.thefooddictator.com/the-hirshon-filipino-roast-pig-cebu-lechon/"},
    {"name": "Lumpia", "url": "https://www.allrecipes.com/recipe/35151/traditional-filipino-lumpia/"},
    {"name": "Pancit", "url": "https://panlasangpinoy.com/filipino-pancit/"},
    {"name": "Sinigang", "url": "https://www.thekitchn.com/sinigang-recipe-23687279"},
    {"name": "Sisig", "url": "https://panlasangpinoy.com/pork-sisig/"},
  ],
  "Singapore": [
    {"name": "Bak Kut Teh", "url": "https://asianinspirations.com.au/recipes/shortcut-singapore-bak-kut-teh/"},
    {"name": "Char Kway Teow", "url": "https://en.wikipedia.org/wiki/Char_kway_teow"},
    {"name": "Chili Crab", "url": "https://www.epicurious.com/recipes/food/views/singaporean-chili-crab"},
    {"name": "Fish Head Curry", "url": "https://www.marionskitchen.com/fish-head-curry/"},
    {"name": "Hainanese Chicken Rice", "url": "https://onehappybite.com/one-pot-hainanese-chicken-rice-with-scallion-oil/"},
    {"name": "Hokkien Mee", "url": "https://asianinspirations.com.au/food-knowledge/the-history-of-pad-thai/"},
    {"name": "Kaya Toast", "url": "https://tarasmulticulturaltable.com/kaya-toast-malaysian-toast-with-coconut-jam/"},
    {"name": "Laksa", "url": "https://asianinspirations.com.au/recipes/singapore-laksa/"},
    {"name": "Roti Prata", "url": "https://www.awesomecuisine.com/recipes/9566/singapore-roti-prata/"},
    {"name": "Satay", "url": "https://www.allbig.com.sg/blogs/news/a-singapore-classic-satay-sticks-and-otah?srsltid=AfmBOoonwQxdLSDyY_gND8bvm1I4zipipFez_mQj9UvMrBAOXGEcZXfm"},
  ],
  "Thailand": [
    {"name": "Boat Noodles", "url": "https://asianinspirations.com.au/food-knowledge/floating-yummies-the-legacy-of-thai-boat-noodles/"},
    {"name": "Green Curry", "url": "https://hot-thai-kitchen.com/green-curry-new-2/"},
    {"name": "Khao Pad", "url": "https://khinskitchen.com/khao-pad/"},
    {"name": "Mango Sticky Rice", "url": "https://www.allrecipes.com/recipe/150313/thai-sweet-sticky-rice-with-mango-khao-neeo-mamuang/"},
    {"name": "Massaman Curry", "url": "https://www.feastingathome.com/massaman-curry/"},
    {"name": "Pad Kra Pao", "url": "https://hot-thai-kitchen.com/pad-kra-pao-beef/"},
    {"name": "Pad Thai", "url": "https://www.recipetineats.com/chicken-pad-thai/"},
    {"name": "Panang Curry", "url": "https://hot-thai-kitchen.com/panang-curry/"},
    {"name": "Som Tam", "url": "https://grantourismotravels.com/thai-som-tam-recipe-green-papaya-salad/"},
    {"name": "Tom Yum", "url": "https://hot-thai-kitchen.com/tom-yum-goong/"},
  ],
  "Timor-Leste": [
    {"name": "Batar Da'an", "url": "https://foreignfork.com/vegetable-medley/"},
    {"name": "Caldeirada", "url": "https://www.tasteatlas.com/caldeirada"},
    {"name": "Cassava", "url": "https://www.thecreolemeltingpot.com/boiled-cassava-mayok-bwi/"},
    {"name": "Corn and Pumpkin Stew", "url": "https://www.internationalcuisine.com/east-timor-batar-daan/"},
    {"name": "Eel Stew", "url": "https://www.saveur.com/recipes/eel-stew-bec-dasan-emilia-romagna-style-recipe/"},
    {"name": "Feijoada", "url": "https://pisangsusu.com/feijoada-from-east-timor-bean-recipe/"},
    {"name": "Grilled Fish", "url": "https://amcarmenskitchen.com/2021/05/12/ikan-pepes-grilled-fish-in-banana-leaves/"},
    {"name": "Ikan Sabuko", "url": "https://amcarmenskitchen.com/2021/03/31/ikan-sabuko-grilled-tamarind-fish/"},
    {"name": "Katupa", "url": "https://en.wikipedia.org/wiki/Ketupat"},
    {"name": "Tukir", "url": "https://en.wikipedia.org/wiki/Cuisine_of_Timor-Leste"},
  ],
  "Vietnam": [
    {"name": "Banh Mi", "url": "https://www.allrecipes.com/recipe/246028/roasted-pork-banh-mi-vietnamese-sandwich/"},
    {"name": "Banh Xeo", "url": "https://www.marionskitchen.com/crispy-vietnamese-pancakes-banh-xeo/"},
    {"name": "Bun Bo Hue", "url": "https://www.marionskitchen.com/bun-bo-hue/"},
    {"name": "Bun Cha", "url": "https://www.andy-cooks.com/es/blogs/recipes/bun-cha?srsltid=AfmBOopKoKJ84j9JulX2xwDOmyKaJV--K767Z11DdPlxstC3_RO0hcah"},
    {"name": "Cao Lau", "url": "https://vietnamnomad.com/eat-drink/cao-lau/"},
    {"name": "Che", "url": "https://www.tasteatlas.com/che"},
    {"name": "Com Tam", "url": "https://asianinspirations.com.au/recipes/vietnamese-broken-rice-with-grilled-pork-com-tam/"},
    {"name": "Goi Cuon", "url": "https://vietnamnomad.com/eat-drink/goi-cuon/"},
    {"name": "Hu Tieu", "url": "https://vietnamnomad.com/eat-drink/hu-tieu/"},
    {"name": "Pho", "url": "https://www.recipetineats.com/vietnamese-pho-recipe/"},
  ],
  
};